package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("title")
    void generatedTest() {
        step("open https://www.yaposhka.kh.ua/", () -> {
            step("// todo: just add selenium action");
        });

        step("open my cabinet", () -> {
            step("// todo: just add selenium action");
        });

        step("set email \"123@ua.ua\"", () -> {
            step("// todo: just add selenium action");
        });

        step("set password \"123445\"", () -> {
            step("// todo: just add selenium action");
        });

        step("submit form", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.yaposhka.kh.ua/'", () ->
            open("https://www.yaposhka.kh.ua/"));

        step("Page title should have text 'Доставка суши Харьков - ЯПОШКА, Заказать суши круглосуточно!'", () -> {
            String expectedTitle = "Доставка суши Харьков - ЯПОШКА, Заказать суши круглосуточно!";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.yaposhka.kh.ua/'", () ->
            open("https://www.yaposhka.kh.ua/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}